### ISSUE TITLE
GIF87a格式的gif图片解析判断错误

### ISSUE THREAD

**Issue by chifandeyu** [CaiJingLong/dart_image_size_getter#23]
GIF87a格式的gif文件头0x47、0x49、0x46、0x38、0x37、0x61, 但是插件里gif只判断GIF89a格式

**Comment by CaiJingLong** [comment]
有示例图片吗，我可以看看怎么改

**Comment by chifandeyu** [comment]
> 有示例图片吗，我可以看看怎么改

我放在百度云了，你可以下载看试试
链接：https://pan.baidu.com/s/1iyayggLTlXLAjWdkW8eQow?pwd=l2ar 
提取码：l2ar
