### ISSUE TITLE
大量jpg图isValid为false

### ISSUE THREAD

**Issue by liangxianshen** [CaiJingLong/dart_image_size_getter#27]
![mmexport1669865708861](https://user-images.githubusercontent.com/8497615/206889695-0628250c-9114-4824-94cc-cedca8701ff5.jpg)
![mmexport1669865705392](https://user-images.githubusercontent.com/8497615/206889709-47145050-2821-43ba-bfd0-8b9c97a8544c.jpg)

**Comment by CaiJingLong** [comment]
The end of your file is the bytes:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/14145407/216499050-a3b670a3-af64-46ed-b68e-0849455f2874.png">

Normal jpeg file is end of '0xFF 0xD9', like next: 

<img width="877" alt="image" src="https://user-images.githubusercontent.com/14145407/216499383-81df1652-3734-475f-a4c4-8c6a59b327ec.png">

--

See the [example](https://github.com/CaiJingLong/dart_image_size_getter/blob/master/example/test/issue_027_test.dart) to know how to use the library get size.
