### ISSUE TITLE
Failed to create image decoder with message 'unimplemented'

### ISSUE THREAD

**Issue by dreammdh** [CaiJingLong/dart_image_size_getter#33]
### Version

2.1.2

### Platforms

Android

### Device Model

none

### flutter info

```sh
Failed to create image decoder with message 'unimplemented'
```

### How to reproduce?

final thumbPathFile = File(thumbPath);
final size = ImageSizeGetter.getSize(FileInput(thumbPathFile));
print('图片宽:${size.width}');
print('图片高:${size.height}');

### Logs

```sh
Failed to create image decoder with message 'unimplemented'
```

### Example code (optional)

```Dart
final thumbPathFile = File(thumbPath);
final size = ImageSizeGetter.getSize(FileInput(thumbPathFile));
print('图片宽:${size.width}');
print('图片高:${size.height}');
```

### Contact

1559664966@qq.com

**Comment by CaiJingLong** [comment]
Provider your image here.
