### ISSUE TITLE
获取宽高相反

### ISSUE THREAD

**Issue by peakerWu** [CaiJingLong/dart_image_size_getter#4]
iOS拍照后的照片，得到图片的宽高值是相反的。比如说下面的图片。正常是3024×4032，但是 `ImageSizGetter.getSize(file)`得到后是 4032x3024
![1](https://user-images.githubusercontent.com/16396005/96068243-1d25cb00-0ece-11eb-9f2c-6b958756c769.jpeg)

**Comment by CaiJingLong** [comment]
图片储存的时候会有方向, 这个读取的是jpeg中存储的原始信息

图片实际显示时会根据角度信息进行"纠错", 让你看到的对应上

![image](https://user-images.githubusercontent.com/14145407/96074183-a17e4b00-0eda-11eb-8e9b-b76a93d2816e.png)

**Comment by peakerWu** [comment]
这个确实是，只能读取原始信息的吗？可不可以读取"纠错"后的信息。因为用户看到的图片的宽高是"纠错"后的。

**Comment by dessonchan** [comment]
能加一個 getOrientation 的 method, 返回 vertical / horizontal 的值嗎? 這樣可以知道須不須要糾錯
